### ISSUE TITLE
Hyperlink in "read more" (minor)

### ISSUE THREAD

**Issue by ridderl** [NLeSC/research-software-directory-frontend#10]
In the "read more" text for SyGMa (https://test.research-software.nl/software/3d-e-chem-sygma) I put a hyperlink, using markdown. However, it is not visible in the frontend that there is a hyperlink. (It is clickable, but the text is black just like the other text.)

**Comment by jspaaks** [comment]
relevant code [here](https://github.com/NLeSC/research-software-directory-frontend/blob/8a97b768194b7fb13be0667e375c2a37787aeb1c/style/templates/_software.scss#L38-L55)

**Comment by Tommos0** [comment]
df97190b42ded8f0a3a992499a6c4ea026b84716
