### ISSUE TITLE
 can we use the lastUpdated date from github as data instead of the datums we have now? 

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/research-software-directory-frontend#16]

**Comment by Tommos0** [comment]
Yes, but not every software item has a github repo, so we'll nee a fallback when this is the case

**Comment by Tommos0** [comment]
Fallback is updatedAt field (last update of our own record, eg through admin interface)
https://github.com/NLeSC/research-software-directory-backend/commit/823e7a9974fb2e6a701352d264f76d5b4d265f98
