### ISSUE TITLE
header_template is not appropriate for index_template

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/research-software-directory-frontend#8]
(relevant [code](https://github.com/NLeSC/research-software-directory-frontend/blob/164bcd87121af5c5a569a25e75909508d9870e37/templates/layout_template.html#L28)). This section should be there for all pages except the index page itself, because then you have ``research software directory`` and ``find software`` pointing to itself. Maybe we should make this conditional somehow?

**Comment by Tommos0** [comment]
dec8947146d437440e5f7d1b5f1dfa82f62db73a
